// <auto-generated />
using System;
using Kolokwium1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium1.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220612081707_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolokwium1.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdMusiclabel")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdMusiclabel");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            IdAlbum = 1,
                            AlbumName = "album1",
                            IdMusiclabel = 1,
                            PublishDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAlbum = 2,
                            AlbumName = "album2",
                            IdMusiclabel = 2,
                            PublishDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolokwium1.Models.Musican", b =>
                {
                    b.Property<int>("IdMusican")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMusican");

                    b.ToTable("Musicans");

                    b.HasData(
                        new
                        {
                            IdMusican = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Nickname = "aaaaaa"
                        },
                        new
                        {
                            IdMusican = 2,
                            FirstName = "Jan",
                            LastName = "Nowak",
                            Nickname = "aaaaaa"
                        });
                });

            modelBuilder.Entity("Kolokwium1.Models.Musican_Track", b =>
                {
                    b.Property<int>("IdMusican")
                        .HasColumnType("int");

                    b.Property<int>("IdTrack")
                        .HasColumnType("int");

                    b.HasKey("IdMusican", "IdTrack");

                    b.HasIndex("IdTrack");

                    b.ToTable("Musican_Tracks");

                    b.HasData(
                        new
                        {
                            IdMusican = 1,
                            IdTrack = 1
                        },
                        new
                        {
                            IdMusican = 2,
                            IdTrack = 2
                        });
                });

            modelBuilder.Entity("Kolokwium1.Models.Musiclabel", b =>
                {
                    b.Property<int>("IdMusicLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMusicLabel");

                    b.ToTable("Musiclabels");

                    b.HasData(
                        new
                        {
                            IdMusicLabel = 1,
                            Name = "musiclabel1"
                        },
                        new
                        {
                            IdMusicLabel = 2,
                            Name = "musiclabel2"
                        });
                });

            modelBuilder.Entity("Kolokwium1.Models.Track", b =>
                {
                    b.Property<int>("IdTrack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("IdMusicAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Trackname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTrack");

                    b.HasIndex("IdMusicAlbum");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            IdTrack = 1,
                            Duration = 2.5f,
                            IdMusicAlbum = 1,
                            Trackname = "track1"
                        },
                        new
                        {
                            IdTrack = 2,
                            Duration = 3.5f,
                            IdMusicAlbum = 2,
                            Trackname = "track2"
                        });
                });

            modelBuilder.Entity("Kolokwium1.Models.Album", b =>
                {
                    b.HasOne("Kolokwium1.Models.Musiclabel", "Musiclabel")
                        .WithMany()
                        .HasForeignKey("IdMusiclabel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musiclabel");
                });

            modelBuilder.Entity("Kolokwium1.Models.Musican_Track", b =>
                {
                    b.HasOne("Kolokwium1.Models.Musican", "Musican")
                        .WithMany("Musican_Tracks")
                        .HasForeignKey("IdMusican")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium1.Models.Track", "Track")
                        .WithMany("Musican_Tracks")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musican");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Kolokwium1.Models.Track", b =>
                {
                    b.HasOne("Kolokwium1.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("IdMusicAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Kolokwium1.Models.Musican", b =>
                {
                    b.Navigation("Musican_Tracks");
                });

            modelBuilder.Entity("Kolokwium1.Models.Track", b =>
                {
                    b.Navigation("Musican_Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
